[package]
name = "ink-stroke-modeler-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
cxx = "1.0"
autocxx = "0.24"
thiserror = "1.0"

[build-dependencies]
anyhow = "1"
miette = {version = "5", features = ["fancy"] }
autocxx-build = "0.24"
cmake = "0.1"
path-slash = "0.2"

[dev-dependencies]
anyhow = "1.0"
svg = "0.10"